[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  exposedByDefault = false

[certificatesResolvers.myresolver.acme]
  email = "support@scan.haidar.fun"
  storage = "/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[log]
  level = "INFO"
